### ISSUE TITLE
Can we change the stacked social media icons on the new topic page to be inline?

### ISSUE THREAD

**Issue by cfarquharson** [canada-ca/design-system-systeme-conception#105]
The stacked social media icons on a topic page seem overkill, especially if there is not promotional block to the left of them.  In that case, there will be an large dead area of white (when there is no promotional item), simply because the social media icons stack vertically instead of going horizontally inline.  I see the handler has been added to each image, thus the reason they stack.  Is that needed?  Usually sites don't give this much focus to social media, especially if it impacts other content blocks on the page.  By vertically aligning them, it allows the template to be more flexible.

![screenshot-featured](https://user-images.githubusercontent.com/2319199/86821468-4a491e80-c03f-11ea-8499-96199c5d575b.PNG)

Is there a reason it wouldn't be more like this? https://test.canada.ca/cra/templates/topic.html

**Comment by jmealing** [comment]
There's CSS support for both inline and stacked, it's just a matter of removing the class "followus-vertical" to go back to inline. 

The guidance wording could be much clearer to show the support for both options, we will make updates for clarity.

**Comment by jmealing** [comment]
@cfarquharson The guidance has been updated to clarify the inline variation.
