### ISSUE TITLE
C: Alerts: Point to or include the research - Alertes : inclure la recherche

### ISSUE THREAD

**Issue by patlaj** [canada-ca/design-system-systeme-conception#11]
We've used this alert pattern in the Travel advice project, and have done independent tests to directly compare this pattern to the current box design. The details of these tests need to either be included in the pattern or in a blog post that we can link to.

**Comment by quidampepin** [comment]
Should this be merged with https://github.com/canada-ca/design-system-systeme-conception/issues/59?

**Comment by quidampepin** [comment]
That's done in the live documentation: https://design.canada.ca/common-design-patterns/contextual-alerts.html#research
