### ISSUE TITLE
Doormats responsive grid sizing for new topic pattern

### ISSUE THREAD

**Issue by cfarquharson** [canada-ca/design-system-systeme-conception#110]
In the new topic pattern: https://design.canada.ca/coded-layout/theme_topic_guidance.html there is only one responsive size (stacked for -xs and -sm vs grid-3 for -md and -lg).  Would it not be best to have a col-md-2 and col-lg-3 (concept here: https://test.canada.ca/cra/templates/topic.html )? 

I know in the agriculture mock-up, the link text is only a few words so the grid3 works well, but even on the homepage of Canada.ca, we go from a 3 to a 2 to a stacked https://www.canada.ca/en.html to account for longer link text in smaller viewports.

**Comment by jmealing** [comment]
Makes sense to me that the doormats should match the same behaviour on the homepage. The ILP could use with the same improvement (it's also jumping from 3 col to 1 col).

**Comment by jmealing** [comment]
@cfarquharson Updated in the theme-topic template. The ILP is under an accessibility/code improvement revision and will be done in the next update.

**Comment by jmealing** [comment]
Done in the ILP too now
