### ISSUE TITLE
Is the Institution byline MANDATORY? 

### ISSUE THREAD

**Issue by mtlesie** [canada-ca/design-system-systeme-conception#137]
Good morning,

I just want to know if the institution byline is mandatory.

One of our QA person pointed out the redundancy of the byline since we have the institution name in the breadcrumbs.
Thanks!

![image](https://user-images.githubusercontent.com/86971329/124488891-611f6f80-dd7e-11eb-901a-27ca4370c21d.png)

**Comment by jkshapiro** [comment]
Nope. Check out https://design.canada.ca/common-design-patterns/institutional-byline.html. If it doesn't say "Mandatory" then it's not mandatory.

See also the complete list of mandatory elements at https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-information-architecture-specification/mandatory-elements.html and note that the byline is not included.

**Comment by mtlesie** [comment]
> 
> 
> Nope. Check out https://design.canada.ca/common-design-patterns/institutional-byline.html. If it doesn't say "Mandatory" then it's not mandatory.
> 
> See also the complete list of mandatory elements at https://www.canada.ca/en/treasury-board-secretariat/services/government-communications/canada-content-information-architecture-specification/mandatory-elements.html and note that the byline is not included.

Thank you very much for your quick answer!!
