### ISSUE TITLE
Question - reporting problems for Canada.ca 

### ISSUE THREAD

**Issue by jeanfrancoislarente** [canada-ca/design-system-systeme-conception#138]
<details>
  <summary>English</summary>
How does an end user report a problem for pages that do not have the “report a problem with this page” functionality?

i tried to log into CRA my account and received the ERR.28 message stating the site was outside of its service hours. There’s a link on that page for “Hours of Service” but when you click on that link it brings you back to an old CRA page which is now replaced with the migration message. 

I couldn’t find anywhere obvious on the site where I could submit a bug report. 

Error page with link to Hours of Service: https://apps7.ams-sga.cra-arc.gc.ca/gol-ged/awsc/amss/enrol/error/ERR.028

Page where link redirects to:

https://www.canada.ca/en/revenue-agency/cra-canada.html?utm_campaign=not-applicable&utm_medium=redirect&utm_source=cra-arc.gc.ca_redirect

Link to where it was trying to redirect: http://www.cra-arc.gc.ca/esrvc-srvce/tx/psssrvcs/hrs-eng.html

Again, reporting here because there is no other obvious place to report it when browsing Canada.ca. Thx!
</details>
<details>
  <summary>Français</summary>

</details>

**Comment by Christopher-O** [comment]
@jeanfrancoislarente I have submitted a ticket to our web portals division and they have stated they will look into this issue.  For future issues, you can indicate them on this page:  https://www.canada.ca/en/revenue-agency/services/e-services/cra-login-services.html  I know it's not the greatest as you cannot explain the issue.  Once the "Report a problem..." forms are replaced with the new widget where you can enter text, that will make it easier to report issues in the future.
