### ISSUE TITLE
Consider renaming to pattern library or template guidelines

### ISSUE THREAD

**Issue by s-duffey** [canada-ca/design-system-systeme-conception#3]
From what is currently available on the Github pages for this project, the content represents less of a design system and more of a pattern library or template guidelines. Design systems refer to very specific libraries based on the [Atomic design methodology](http://atomicdesign.bradfrost.com/chapter-2/), by Brad Frost, which breaks down design to individual components prior to creating more complex components, patterns and templates. 

If you look at other design systems, information is provided at the "atomic" level for each component, including documentation, the individual design (usually in Adobe Illustrator or Sketch), and the HTML or React code for each individual component. It creates more of puzzle pieces which designers are then free to put together in different combinations to create webpages. Often, in design systems common layouts (i.e. login pages, home pages, etc.) are provided for reference, but they are less prescriptive than a pattern library.  Usually there are only a few most common layouts provided in design systems, and designers and developers are given much more freedom to combine individual components as they see fit to create applications. 

Here are popular design systems for reference:

[Semantic.ui ](https://semantic-ui.com/)
[Google Material Design](https://material.io/design/)
[Australian Design System](https://designsystem.gov.au/) 
[Carbon Design System](http://www.carbondesignsystem.com/)
[Shopify Polaris](https://polaris.shopify.com/)
[Clarity Design System](https://vmware.github.io/clarity/)
[U.S. Design System ](https://designsystem.digital.gov/)

**Comment by quidampepin** [comment]
Your description of a design system is pretty much where we want to take these patterns and templates: provide reusable code snippets, provide examples of page layouts, provide freedom of combination to designers, and find a way to engage the community to collaborate on the design system. Only a small set of templates would be mandatory, mostly for the main institutional presence and the top layers of Canada.ca. 

This will take a few months. Currently, all the patterns and templates are tied to policy (in the IA specs, through the Directive on the management of Communications). This repo is only the first step towards building a real design system: decoupling the actual the patterns/templates from the policy instrument. The second step will be a new version of the IA specs, redefining (and narrowing down) what is mandatory for all departments, and referencing these patterns (outside of the specs). Then we'll be able to iteratively and progressively provide code for existing patterns and page layouts, consider new patterns, potentially dropping some, etc.
